repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        files: ^enginecore/
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
        files: ^dashboard/
        exclude_types: [svg, png]
